name: Publish Github Release

on:
  pull_request:
    branches:
      - develop
    types: [ closed ]

jobs:
  publish-github-release:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: publish-linked-draft-release
        name: Publish linked draft release
        env:
          GH_TOKEN: ${{ github.token }}
          PR_ID: ${{ github.event.pull_request.number }}
          PR_LABELS: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
        run: |
          # find the github release id from labels
          RELEASE_ID=$(echo PR_LABELS | sed 's/.*RID_\([^,]*\).*/\1/')
          # publish the github release
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID \
            -F draft=false \
            -F make_latest=true > release.json
          # update PR description
          cat release.json | jq -r .body > body.md
          echo -e "\n\nPublished release: $(cat release.json | jq -r .html_url)" >> body.md
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/pulls/$PR_ID \
            -F 'body=@body.md'
